config/routes.rb
Rails.application.routes.draw do
  resources :images

  root 'images#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
  validates_uniqueness_of :img_src

  def info
    if self.size
      "#{self.width} * #{self.height} #{sizeFormat}"
    else
      ""
    end
  end

  def isBig?
    # true if self.height > 2000
    if self.height
      return true if self.height > 2000
    end
    false
  end

  def sizeFormat
    if self.size/1000000 == 0
      return "#{self.size/1000}KB"
    else
      return "#{self.size/1000000}MB"
    end
  end

  def gif?
    return img_src.include?".gif" if img_src
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    params[:per_page] ||= 5

    @images = Image.order("created_at DESC").paginate(:page => params[:page], :per_page => params[:per_page])
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:img_src, :acv_comment, :width, :height, :size)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_footer.html.erb
<%= will_paginate @images, :style => 'color:chocolate;', :inner_window => 1, :outer_window => 0 %>
<br>
<br>
<h1> </h1>

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :img_src %><br>
    <%= f.text_field :img_src %>
  </div>
  <div class="field">
    <%= f.label :acv_comment %><br>
    <%= f.text_field :acv_comment %>
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.number_field :width %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.number_field :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/_img.html.erb
<div class='col-md-3 card' style="padding:0px;padding-top:1px">
    <% if @img.gif? %>
        <a href="<%= image_path(@img) %>">
            <div>
            <h5><%= @img.id %> <%= @img.acv_comment %></h5>
            <small><%= @img.info %>（动态图，点击加载）</small>
            </div>
        </a>
        <img class="lazy" data-original="<%= @img.img_src %>" src="<%= image_path('grey.gif') %>" width="765" height="574">
    <% elsif @img.isBig? %>
        <a href="<%= image_path(@img) %>">
            <h5><%= @img.id %> <%= @img.acv_comment %></h5>
            <small><%= @img.info %>（加长夜用图片，点击加载）</small>
        </a>
        <img class="lazy" data-original="<%= @img.img_src %>" src="<%= image_path('grey.gif') %>" width="765" height="574">
    <% else %>
        <a href="<%= image_path(@img) %>">
            <h5><%= @img.id %> <%= @img.acv_comment %></h5>
        </a>
        <img src="<%= @img.img_src %>">
    <% end %>
</div>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<div class='row'>
  <% @images.each do |img| %>
    <% @img = img %>
    <%= render 'img' %>
  <% end %>
</div>
<%= render 'footer' %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<% @img = @image %>
<div class="row">
<%= render 'img' %>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>PGonjay</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
	<%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="container">
			<a class="navbar-brand" href="<%= root_path %>">无聊图</a>
		</div>
	</nav>
	<div class="container-fluid">
		<%= yield %>  
	</div>

</body>
</html>